#
# Makefile for the kernel Sensor device drivers.
#

# Object files in subdirectories

obj-$(CONFIG_J4FS)			+= j4fs/
obj-$(CONFIG_FM_SI4709)			+= fm_si4709/
obj-$(CONFIG_VIBETONZ)			+= vibetonz/
obj-$(CONFIG_VOODOO_LOUDER)		+= mc1n2_voodoo/
obj-$(CONFIG_VOODOO_SCREEN_TUNER)	+= ld9040_voodoo/
