#!/sbin/busybox sh

# dummy blocks extract
/sbin/busybox tar xvf /res/misc/dev.tar

# check boot rom
/sbin/busybox mount -t ext4 /dev/block/mmcblk0p9 /system
if [ "`/sbin/busybox grep se.infra /system/build.prop`" ]; then
  /sbin/busybox umount /system
  exec /vendor/samsung/init.samsung
else
  /sbin/busybox umount /system
  exec /vendor/aosp/init.aosp
fi

