#!/sbin/busybox sh

# dummy blocks extract
busybox tar xvf /res/misc/dev.tar

# check boot rom
busybox mount -t ext4 /dev/block/mmcblk0p10 /xdata
if [ -f /xdata/boot.conf ]; then
  if [ "`/sbin/busybox grep secondary /xdata/boot.conf`" ]; then
    busybox umount /xdata
    # secondary rom boot
    busybox mount -t ext4 /dev/block/mmcblk0p12 /system
    if [ "`/sbin/busybox grep se.infra /system/build.prop`" ]; then
      busybox umount /system
      exec /vendor/samsung/init.samsung secondary
    else
      busybox umount /system
      exec /vendor/aosp/init.aosp secondary
    fi
  else
    busybox umount /xdata
    busybox mount -t ext4 /dev/block/mmcblk0p9 /system
    # primary rom boot
    if [ "`/sbin/busybox grep se.infra /system/build.prop`" ]; then
      busybox umount /system
      exec /vendor/samsung/init.samsung primary
    else
      busybox umount /system
      exec /vendor/aosp/init.aosp primary
    fi
  fi
else
  busybox umount /xdata
  busybox mount -t ext4 /dev/block/mmcblk0p9 /system
  if [ "`/sbin/busybox grep se.infra /system/build.prop`" ]; then
    busybox umount /system
    exec /vendor/samsung/init.samsung none
  else
    busybox umount /system
    exec /vendor/aosp/init.aosp none
  fi
fi
